# Generated by Django 3.1.1 on 2020-09-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200917_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='crmv',
            field=models.CharField(max_length=45),
        ),
    ]
