# Generated by Django 3.1.1 on 2020-09-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200918_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medicacao',
            field=models.ManyToManyField(blank=True, to='core.Medicacao'),
        ),
    ]
