# Generated by Django 3.1.1 on 2020-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200919_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacina',
            name='descricao',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
