# Generated by Django 3.1.1 on 2020-09-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200919_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adocao',
            name='cachorro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cachorro'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='guardiao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa'),
        ),
    ]
