# Generated by Django 3.1.1 on 2020-09-19 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20200919_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinario',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='veterinario',
            name='credenciais',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veterinario',
            name='pessoa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
    ]
