# Generated by Django 3.1.1 on 2020-09-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200919_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veterinario'),
        ),
    ]
