# Generated by Django 3.1.1 on 2020-09-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200919_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacina',
            name='deleted_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='cachorro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cachorro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacina',
            name='descricao',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='vacina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.vacina'),
        ),
    ]
