# Generated by Django 3.1.1 on 2020-09-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200921_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='medicacao',
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Medicacao',
        ),
    ]
