# Generated by Django 3.1.1 on 2020-09-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200921_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cachorros'),
        ),
    ]
